# NOTE: update this with your service name
service: eimovina-be

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

custom:
  appSync:
    - ${file(appsync-api.yml)}

functions:
  fetchProperty:
    handler: functions/getProperty.main

resources:
  Resources:
    PropertyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-nekretnina
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
