# NOTE: update this with your service name
service: eimovina-be

# Create an optimized package for our functions
package:
  individually: true
  exclude:
    - package-lock.json
    - package.json

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    ALGOLIA_APP_ID: ${ssm:eimovina-be-algolia-app-id}
    ALGOLIA_ADMIN_API_KEY: ${ssm:eimovina-be-algolia-admin-api-key}
    ALGOLIA_INDEX_NAME: eimovina-be-property-index


custom:
  stage: ${opt:stage, self:provider.stage}
  appSync:
    - ${file(appsync-api.yml)}

functions:
  syncPropertyAlgolia:
    handler: functions/syncPropertyAlgolia.main
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt PropertyTable.StreamArn

  getProperties:
    handler: functions/getProperties.main
  
  confirmUserSignup:
    handler: functions/confirmUserSignup.main
    environment:
      USERS_TABLE: !Ref UsersTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn
  
  updateUser:
    handler: functions/updateUser.main
    environment:
      USERS_TABLE: !Ref UsersTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource: !GetAtt UsersTable.Arn

  # loadPropertiesData:
  #   handler: scripts/loadPropertiesData.main
  #   environment:
  #     USERS_TABLE: !Ref PropertiesTable
  #   iamRoleStatements:
  #     - Effect: Allow
  #       Action: dynamodb:UpdateItem
  #       Resource: !GetAtt PropertiesTable.Arn

resources:
  Resources:
    PropertyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: property-table
    
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: user-table
        
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_LINK
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireUppercase: true
            RequireSymbols: true
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: true
            Mutable: true
        LambdaConfig:
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn

    CognitoDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties: 
        Domain: eimovina-be
        UserPoolId: !Ref CognitoUserPool

    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt CognitoUserPool.Arn

    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED


  