name: deploy backend

on:
  push:
    branches: [ dev ]
    paths:
      - "eimovina-be/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: npm ci
      working-directory: eimovina-be
      run: npm ci

    - name: install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        
        rm awscliv2.zip
        rm -r ./aws

    - name: Configure AWS DEV Credentials
      if: github.ref == 'refs/heads/dev'
      working-directory: eimovina-be
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/dev-ci-role
        role-duration-seconds: 1200
        role-session-name: dev_ci_user

    - name: Configure AWS PROD Credentials
      if: github.ref == 'refs/heads/main'
      working-directory: eimovina-be
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/prod-ci-role
        role-duration-seconds: 1200
        role-session-name: prod_ci_user

    - name: deploy to dev
      if: github.ref == 'refs/heads/dev'
      run: npm run sls -- deploy -s dev
    
    - name: deploy to prod
      if: github.ref == 'refs/heads/main'
      run: npm run sls -- deploy -s prod