name: deploy frontend

on:
  push:
    branches: [ dev ]
    paths:
      - "eimovina-fe/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: yarn install
      working-directory: eimovina-fe
      run: yarn install

    - name: yarn build
      working-directory: eimovina-fe
      run: yarn build

    - name: Configure DEV AWS Credentials
      if: github.ref == 'refs/heads/dev'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/dev-ci-role
        role-duration-seconds: 1200
        role-session-name: dev_ci_user

    - name: Configure PROD AWS Credentials
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/prod-ci-role
        role-duration-seconds: 1200
        role-session-name: prod_ci_user

    - name: deploy to dev 
      if: github.ref == 'refs/heads/dev'
      run: aws s3 sync eimovina-fe/build/ s3://${{ secrets.DEV_BUCKET_NAME }} --delete

    - name: deploy to prod 
      if: github.ref == 'refs/heads/main'
      run: aws s3 sync eimovina-fe/build/ s3://${{ secrets.PROD_BUCKET_NAME }} --delete