name: deploy frontend

on:
  push:
    branches: [ dev ]
    paths:
      - "eimovina-fe/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure DEV AWS Credentials
      if: github.ref == 'refs/heads/dev'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/dev-ci-role
        role-duration-seconds: 1200
        role-session-name: dev_ci_user

    - name: Build React App
      working-directory: eimovina-fe
      run: npm ci && npm run build

    - name: Deploy app build to S3 bucket
      if: github.ref == 'refs/heads/dev'
      run: aws s3 sync eimovina-fe/build/ s3://${{ secrets.DEV_BUCKET_NAME }} --delete